onlyBuiltDependencies:
  - esbuild
  - skia-canvas
patchedDependencies:
  isomorphic-git: /home/austin/git-visualizer/patches/isomorphic-git.patch
  '@tsconfig/node-lts': patches/@tsconfig__node-lts.patch
